# Generated by Django 4.1.4 on 2022-12-30 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_alter_message_content_type_userstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": "['textmessage']"},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
