# Generated by Django 4.1.4 on 2022-12-30 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("chat", "0004_alter_message_content_type_alter_userstatus_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatus",
            name="id",
        ),
        migrations.AlterField(
            model_name="message",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": "['textmessage']"},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
