# Generated by Django 4.1.4 on 2022-12-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="avatar",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("color", models.CharField(max_length=255)),
                ("image", models.FileField(null=True, upload_to="")),
            ],
        ),
    ]
